### ISSUE TITLE
Easier way to install 

### ISSUE THREAD

**Issue by amin3mej** [pouriya/tir#4]
Hi,
First of all, thank you for your effort in making this software.
But, I want to ask is there any easier way to install this software?
I read the README file and i got it that I have to install lots of dependencies for using this. 
It's good to build a way to install with only one command an enjoy it.
thanks.

**Comment by Pouriya-Jahanbakhsh** [comment]
Hi. you're welcome. Most of dependencies such as Python3, setuptools, etc by default are installed on most linux distros. I could have publish it on PyPi and you could install it with just `pip3 install tir`. But you had to have `python3` and `pip3` too. Since I don't have Windows installed, I could not wrap it in one package. I leave this issue open and hope for someone else's help. Thank you.

**Comment by amin3mej** [comment]
Thanks. But I'm using mac.

**Comment by zumoshi** [comment]
Adding it to PyPi would definitely help. It would also make updating easier. It can be at most installed with two commands in most systems from PyPi.

For example on mac: (via [brew](https://docs.brew.sh/Installation))
```
brew install python3
pip3 install tir
```
Alternatives to HomeBrew for Mac:
- [MacPorts](https://www.macports.org/install.php) `port install python38`
- [ZeroInstall](https://docs.0install.net/details/macos/)

Or on windows: (via [chocolatey](https://chocolatey.org/install))
```
choco install python
pip3 install tir
```
Alternatives to chocolatey for windows:
- [Ninite](https://ninite.com/) (just check python and click install)
- [Scoop](https://scoop.sh/) `scoop install python`
- [Just Install](https://just-install.github.io/) `just-install python3`

While you could provide single package .exe or .app files for windows/mac I don't think people who would appreciate a command-line tool vs a GUI would prefer that to have a python installation. Not to mention embedding python would not only increase the package size but also add extra maintenance burden of keeping that updated on every release.

**Comment by zumoshi** [comment]
Was this added to PyPi?

I don't see any references to the `pip` installation method in the ReadMe. if not why close the issue?
